name: DBT test - Google POI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["dbt - build datamart google_poi"]  # optional chaining
    types: [completed]

jobs:
  tests:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write SA keyfile for dbt
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > sa.json

      - name: Create dbt profile
        run: |
          mkdir -p .dbt
          cat > .dbt/profiles.yml << 'EOF'
          demo2:
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                project: eneco-488308
                dataset: staging
                keyfile: sa.json
                threads: 4
                location: europe-west4
          EOF

      - name: dbt deps
        env:
          DBT_PROFILES_DIR: .dbt
        run: |
          dbt deps

      - name: dbt test (DWH)
        env:
          DBT_PROFILES_DIR: .dbt
        run: |
          dbt test --select dim_google_poi fact_google_poi
